env:
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Builder"
  timeout_in: 120m
  container:
      image: ghcr.io/catthehacker/ubuntu:full-22.04
      cpu: 8
      memory: 32G

  sod:
      - apt update -y && curl -sL https://raw.githubusercontent.com/SA-17/cr/main/hil.bash | bash

  Sync_script:
      - curl -sL https://raw.githubusercontent.com/SA-17/cr/main/download.sh | bash
